[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[[headers]]
  for = "/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
